  deploy:
    name: Deploy to IIS (Dev)
    needs: build
    runs-on: [self-hosted, windows, x64, windows-dev]   # match your runner labels
    env:
      ARTIFACT_DIR: C:\actions\api-publish
      HEALTH_URL:  http://localhost:8080/health
    steps:
      - name: Download publish artifact
        uses: actions/download-artifact@v4
        with:
          name: api-publish
          path: ${{ env.ARTIFACT_DIR }}

      - name: Checkout repo (for deploy script)
        uses: actions/checkout@v4

      - name: List downloaded files (debug)
        shell: powershell
        run: |
          Write-Host "PS version:"; $PSVersionTable
          Write-Host "Artifact dir: $env:ARTIFACT_DIR"
          Get-ChildItem -Recurse $env:ARTIFACT_DIR |
            Select-Object FullName,Length,LastWriteTime |
            Sort-Object FullName

      - name: Deploy via PowerShell
        shell: powershell
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          & "${{ github.workspace }}\infra\deploy-api.ps1" `
            -ArtifactDir "${{ env.ARTIFACT_DIR }}" `
            -HealthUrl   "${{ env.HEALTH_URL }}"
